version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tbd
      POSTGRES_DB: mockpfi
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  node:
    image: node:20.4.0
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:tbd@postgres:5432/mockpfi
    command: >
      sh -c "
        npm install &&
        curl -fsSL https://github.com/amacneil/dbmate/releases/download/v1.12.1/dbmate-linux-amd64 -o dbmate &&
        chmod +x dbmate &&
        mv dbmate /usr/local/bin &&
        ./db/scripts/migrate &&
        npm run seed-offerings &&
        npm run server &
        SERVER_PID=$! &&
        sleep 5 &&
        npm run test &&
        kill $SERVER_PID
      "
